CREATE TABLE Grp
(
Id_Grp INTEGER NOT NULL PRIMARY KEY IDENTITY,
Number_grp VARCHAR(20) NOT NULL,
Napr VARCHAR(50) NOT NULL,
Inst VARCHAR(20) NOT NULL,
Kaf VARCHAR(20) NOT NULL
);

CREATE TABLE Subj
(
Id_Subj INTEGER NOT NULL PRIMARY KEY IDENTITY,
Name_sbj VARCHAR(70) NOT NULL,
Type_z VARCHAR(50) NOT NULL CHECK (Type_z IN ('Экзамен', 'Зачет с оценкой', 'Зачет без оценки'))
);

CREATE TABLE Tchr
(
Id_tchr INTEGER NOT NULL PRIMARY KEY IDENTITY,
Name_tchr VARCHAR(100) NOT NULL,
E_mail VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL,
Exper INTEGER NOT NULL CHECK (Exper >= 0 AND Exper <= 100)
);

CREATE TABLE Student
(
Id_stud INTEGER NOT NULL PRIMARY KEY IDENTITY,
Name_stud VARCHAR(100) NOT NULL,
E_mail VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL,
Adress VARCHAR(50) NOT NULL,
Stat VARCHAR(50) NOT NULL CHECK (Stat IN ('Абитуриент', 'Бакалавр', 'Магистр', 'Аспирант')),
Acad_z INTEGER NOT NULL CHECK (Acad_z = 0 OR Acad_z = 1),
Id_Grp INTEGER NOT NULL FOREIGN KEY REFERENCES Grp (Id_Grp) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Grp_Subj
(
Id_Subj INTEGER NOT NULL FOREIGN KEY REFERENCES Subj (Id_Subj) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Grp INTEGER NOT NULL FOREIGN KEY REFERENCES Grp (Id_Grp) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_Grp_Subj PRIMARY KEY(Id_Subj, Id_Grp),
CONSTRAINT Check_Grp_Subj CHECK (Id_Subj >=0 AND Id_Grp >= 0)
);

CREATE TABLE Tchr_Subj
(
Id_Subj INTEGER NOT NULL FOREIGN KEY REFERENCES Subj (Id_Subj) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Tchr INTEGER NOT NULL FOREIGN KEY REFERENCES Tchr (Id_Tchr) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_Tchr_Subj PRIMARY KEY(Id_Subj, Id_Tchr),
CONSTRAINT Check_Tchr_Subj CHECK (Id_Subj >=0 AND Id_Tchr >= 0)
);

CREATE TABLE AccAttend
(
Id_AccAttend INTEGER NOT NULL PRIMARY KEY IDENTITY,
Id_Stud INTEGER NOT NULL FOREIGN KEY REFERENCES Student (Id_Stud) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Subj INTEGER NOT NULL FOREIGN KEY REFERENCES Subj (Id_Subj) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Tchr INTEGER NOT NULL FOREIGN KEY REFERENCES Tchr (Id_Tchr) ON DELETE CASCADE ON UPDATE CASCADE,
TypeClass VARCHAR(50) NOT NULL CHECK (TypeClass IN ('Лекция', 'Практика', 'ЛР', 'Экзамен', 'Консультация')),
Presense INTEGER NOT NULL CHECK (Presense = 0 OR Presense = 1),
DateClass DATETIME NOT NULL
);

CREATE TABLE AccMarks
(
Id_AccMarks INTEGER NOT NULL PRIMARY KEY IDENTITY,
Id_Stud INTEGER NOT NULL FOREIGN KEY REFERENCES Student (Id_Stud) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Subj INTEGER NOT NULL FOREIGN KEY REFERENCES Subj (Id_Subj) ON DELETE CASCADE ON UPDATE CASCADE,
Id_Tchr INTEGER NOT NULL FOREIGN KEY REFERENCES Tchr (Id_Tchr) ON DELETE CASCADE ON UPDATE CASCADE,
SemMark INTEGER NOT NULL CHECK (SemMark >= 2 AND SemMark <= 5),
Rate DECIMAL(3,2) NOT NULL CHECK (Rate >= 2 AND Rate <= 5)
);

CREATE TABLE KM
(
Id_KM INTEGER NOT NULL PRIMARY KEY IDENTITY,
Id_AccMarks INTEGER NOT NULL FOREIGN KEY REFERENCES AccMarks (Id_AccMarks) ON DELETE CASCADE ON UPDATE CASCADE,
Name_KM VARCHAR(100) NOT NULL,
KMMark INTEGER NOT NULL CHECK (KMMark >= 2 AND KMMark <= 5)
);

CREATE TABLE Work
(
Id_Work INTEGER NOT NULL PRIMARY KEY IDENTITY,
Id_KM INTEGER NOT NULL FOREIGN KEY REFERENCES KM (Id_KM) ON DELETE CASCADE ON UPDATE CASCADE,
Name_Work VARCHAR(100) NOT NULL,
TypeWork VARCHAR(50) NOT NULL CHECK (TypeWork IN ('Практ', 'КР', 'ЛР', 'ТР')),
IsDone INTEGER NOT NULL CHECK (IsDone = 0 OR IsDone = 1),
WorkMark INTEGER NOT NULL CHECK (WorkMark >= 2 AND WorkMark <= 5),
);

